{
 "title": "Client Metrics (Consumer)",
 "description": "Autogenerated Dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "rate(python_gc_objects_collected_total[1m])",
   "type": "graph",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(python_gc_objects_collected_total[1m])"
    }
   ]
  },
  {
   "title": "rate(python_gc_objects_uncollectable_total[1m])",
   "type": "graph",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(python_gc_objects_uncollectable_total[1m])"
    }
   ]
  },
  {
   "title": "rate(python_gc_collections_total[1m])",
   "type": "graph",
   "gridPos": { "h": 11, "w": 5, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(python_gc_collections_total[1m])"
    }
   ]
  },
  {
   "title": "rate(process_start_time_seconds[1m])",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_start_time_seconds[1m])"
    }
   ]
  },
  {
   "title": "rate(process_open_fds[1m])",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(process_open_fds[1m])" }
   ]
  },
  {
   "title": "rate(python_info[1m])",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(python_info[1m])" }
   ]
  },
  {
   "title": "rate(process_virtual_memory_bytes[1m])",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 9, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_virtual_memory_bytes[1m])"
    }
   ]
  },
  {
   "title": "rate(process_resident_memory_bytes[1m])",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 13, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes[1m])"
    }
   ]
  },
  {
   "title": "rate(process_cpu_seconds_total[1m])",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 17, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])"
    }
   ]
  },
  {
   "title": "rate(process_max_fds[1m])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(process_max_fds[1m])" }
   ]
  },
  {
   "title": "rate(kafka_consumer_reply_queue[1m])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_reply_queue[1m])"
    }
   ]
  },
  {
   "title": "rate(kafka_consumer_consumed_records_rate[1m])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_consumed_records_rate[1m])"
    }
   ]
  },
  {
   "title": "rate(kafka_consumer_consumed_bytes_rate[1m])",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_consumed_bytes_rate[1m])"
    }
   ]
  },
  {
   "title": "rate(kafka_consumer_records_lag[1m])",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_records_lag[1m])"
    }
   ]
  }
 ]
}