{
 "title": "Client Metrics (Producer)",
 "description": "Autogenerated Dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "rate(python_gc_objects_collected_total[1m])",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(python_gc_objects_collected_total[1m])"
    }
   ]
  },
  {
   "title": "rate(python_gc_objects_uncollectable_total[1m])",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(python_gc_objects_uncollectable_total[1m])"
    }
   ]
  },
  {
   "title": "rate(python_gc_collections_total[1m])",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(python_gc_collections_total[1m])"
    }
   ]
  },
  {
   "title": "rate(python_info[1m])",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(python_info[1m])" }
   ]
  },
  {
   "title": "rate(process_virtual_memory_bytes[1m])",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_virtual_memory_bytes[1m])"
    }
   ]
  },
  {
   "title": "rate(process_resident_memory_bytes[1m])",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes[1m])"
    }
   ]
  },
  {
   "title": "rate(process_start_time_seconds[1m])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_start_time_seconds[1m])"
    }
   ]
  },
  {
   "title": "rate(process_cpu_seconds_total[1m])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 5, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])"
    }
   ]
  },
  {
   "title": "rate(process_open_fds[1m])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 11, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(process_open_fds[1m])" }
   ]
  },
  {
   "title": "rate(process_max_fds[1m])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(process_max_fds[1m])" }
   ]
  },
  {
   "title": "rate(kafka_producer_reply_queue[1m])",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_reply_queue[1m])"
    }
   ]
  },
  {
   "title": "rate(kafka_producer_queue_msg_cnt[1m])",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_queue_msg_cnt[1m])"
    }
   ]
  },
  {
   "title": "rate(kafka_producer_queue_msg_size[1m])",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_queue_msg_size[1m])"
    }
   ]
  },
  {
   "title": "rate(kafka_producer_inflight_msg_cnt[1m])",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_inflight_msg_cnt[1m])"
    }
   ]
  },
  {
   "title": "rate(kafka_producer_queue_latency_avg[1m])",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_queue_latency_avg[1m])"
    }
   ]
  },
  {
   "title": "rate(kafka_producer_broker_latency_avg[1m])",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_broker_latency_avg[1m])"
    }
   ]
  },
  {
   "title": "rate(kafka_producer_batch_size_bytes_avg[1m])",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_batch_size_bytes_avg[1m])"
    }
   ]
  },
  {
   "title": "rate(kafka_producer_batch_size_avg[1m])",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_batch_size_avg[1m])"
    }
   ]
  },
  {
   "title": "rate(kafka_producer_request_rate[1m])",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_request_rate[1m])"
    }
   ]
  },
  {
   "title": "rate(kafka_producer_request_bytes_rate[1m])",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_request_bytes_rate[1m])"
    }
   ]
  },
  {
   "title": "rate(kafka_producer_response_rate[1m])",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_response_rate[1m])"
    }
   ]
  },
  {
   "title": "rate(kafka_producer_response_bytes_rate[1m])",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_response_bytes_rate[1m])"
    }
   ]
  }
 ]
}